spring:
  application:
    name: stocklistener

  threads:
    virtual:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 200ms
      connect-timeout: 200ms

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3:8b #qwen3:8b
        options:
          temperature: 0.1   # low = deterministic JSON output
          format: json       # forces model to respond with JSON only

  lifecycle:
    timeout-per-shutdown-phase: 10s

server:
  port: 8000
  shutdown: graceful

massive:
  api-key: ${MASSIVE_API_KEY}
  symbols: AM.*

# Filter stocks before we show interest. Bar must be at least 2 dollar and volume must be at least 50k
filter:
  min-close: 0.1
  min-volume: 500

patterns:
  breakout:
    stop: 0.9
    target: 1.05
  invertedV:
    stop: -1.35
    target: 2.0
  unsharpen:
    stop: 0.97
    target: 1.06

ollama:
  breakout:
    min-confidence: 70   # minimum Ollama confidence % to emit a signal

logging:
  level:
    ROOT: INFO
    za.co.sfh: DEBUG